### ISSUE TITLE
Flutter  dropzone is not working 

### ISSUE THREAD

**Issue by Amodh2022** [deakjahn/flutter_dropzone#64] opened 2023-06-23 05:50 UTC
I am using flutter dropzone but its showing target windows is not supported how do i fix this issue please elp me with this

**Comment by Amodh2022** [comment] 2023-06-23 05:53
<img width="861" alt="target" src="https://github.com/deakjahn/flutter_dropzone/assets/103436151/083dbd00-2710-487f-8495-abf8c9a38e51">

**Comment by deakjahn** [comment] 2023-06-23 10:41
Duplicate of https://github.com/deakjahn/flutter_dropzone/issues/61. Please, see the comments there if you can come up with a log.

**Closed by deakjahn** 2023-06-23 10:41 UTC
